EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = "587"
EMAIL_USE_TLS = "true"
EMAIL_USE_SSL = "false"
EMAIL_FROM = "paperscout.journalservice@gmail.com"
EMAIL_USER = "paperscout.journalservice@gmail.com"
EMAIL_PASSWORD = "dbuasytzibzqtzlz"  # 16 Zeichen, KEINE Leerzeichen
EMAIL_SENDER_NAME = "Paperscout Journal Service"

PAPERSCOUT_OPENAI_API_KEY = "sk-proj-..."
CROSSREF_MAILTO = "naomi.rusch@fh-swf.de"

